
// This file is automatically generated. Do not edit it directly.
import { supabase } from '@/lib/supabase';
import type { Database } from './types';

// This export is kept for compatibility but we recommend using the client from lib/supabase.ts
export { supabase };
